name: Copy Dist to actions Branch

on:
  push:
    branches:
      - main  # Modify this branch name if needed

jobs:
  copy-dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Copy dist/ folder
        run: |
          mkdir actions
          cp -R dist/* actions/

      - name: Checkout actions branch
        uses: actions/checkout@v2
        with:
          ref: actions
          path: actions

      - name: Commit and push changes
        run: |
          cd actions
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "Copy dist/ folder to actions branch"
          git push

